### PR TITLE
fix match empty levels #24

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
I have added the test on abstracts tests of mqemitter

**Comment by robertsLando** [comment]
@mcollina

**Comment by mcollina** [comment]
I've pushed out a new version of mqemitter. Can you bump that in the package.json? Thanks

**Comment by robertsLando** [comment]
@mcollina Done. Can you create a patch release? So I can fix aedes-tests :)

**Pull request merged**
