### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by mcollina** [comment]
Why closing?

**Comment by kibertoad** [comment]
It's very flaky. See different attempts here: https://github.com/kibertoad/mqemitter-redis/pulls

I wonder why CI is all green for PRs that were merged last week.

**Comment by mcollina** [comment]
Doesn't look flaky. It's failing on 22

**Comment by kibertoad** [comment]
Huh, interesting. E. g. https://github.com/kibertoad/mqemitter-redis/pull/4 failed on Node 14, https://github.com/kibertoad/mqemitter-redis/pull/1 failed on Node 16.

But if it fails primarily on Node 22, then it's an easier problem to solve. I'll look into it, if other versions are not a concern.

**Comment by mcollina** [comment]
This should pass now.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
