### PR TITLE
fix: add types definitions

### PR DESCRIPTION
**Pull request by getlarge**

### CODE REVIEW

**Comment by mcollina** [comment]
Could you write some tests for the types with http://npm.im/tsd?

**Comment by getlarge** [comment]
Is that enough ?
I suppose [mqemitter](https://github.com/mcollina/mqemitter/blob/master/mqemitter.d.ts) should also get some ?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@getlarge yes definitely. Could you add them to mqemitter first? There is likely something to reuse here.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
