### PR TITLE
Fix packet from another

### PR DESCRIPTION
**Pull request by cuongtl1992**
Issue when our emitter connect to redis which use for another system, it can take some msg from another it make wrong and issue
@mcollina pls review my commit and make a new release

### CODE REVIEW

**Comment by cuongtl1992** [comment]
@mcollina i run npm test and fix some error. tks

**Comment by cuongtl1992** [comment]
@mcollina u can support me make a release soon. i using it for my production project.

**Comment by mcollina** [comment]
This needs a _new_ unit test to cover for this case.

**Comment by mcollina** [comment]
Closing for no activity, feel free to reopen if needed.

**Pull request closed without merging**
